# Generated by Django 5.1 on 2024-08-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor_management', '0001_initial'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('quarterly', 'Quarterly Report'), ('annual', 'Annual Report')], max_length=20)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('report_pdf', models.FileField(upload_to='financial_reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor_management.donor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_budget', to='project_management.project')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('expense_type', models.CharField(choices=[('project', 'Project Expense'), ('administrative', 'Administrative Expense'), ('other', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance_management.budget')),
            ],
        ),
    ]
