# Generated by Django 5.1 on 2024-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
