# Generated by Django 5.1 on 2024-08-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_for_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('request_for', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Donation_Gallery',
        ),
    ]
