# Generated by Django 5.1 on 2024-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0005_request_for_donation_rename_gallery_donation_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='identity_card',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
