# Generated by Django 5.1 on 2024-08-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0006_volunteer_identity_card_volunteer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
