# Generated by Django 5.1 on 2024-08-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0008_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
