# Generated by Django 5.1 on 2024-08-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0010_alter_campaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(),
        ),
    ]
