# Generated by Django 5.1 on 2024-09-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0013_donation_amount_donation_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='amount_donated',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='donor_management.campaign'),
        ),
    ]
