# Generated by Django 5.1.5 on 2025-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_management', '0015_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
